#!/usr/bin/env node
/**
 * Generates src/environments/environment.prod.ts from environment variables
 * before a production build. Runs automatically via the `prebuild` npm script
 * (so `npm run build` triggers it on Netlify and locally).
 *
 * Local builds: reads a .env file if present (same vars as Netlify).
 * If FIREBASE_API_KEY is missing, the placeholder file is left untouched and
 * the app falls back to the in-browser setup screen — the build never breaks.
 */

const fs = require('fs');
const path = require('path');

// ── Load .env for local builds (Netlify injects via process.env) ────
try {
  fs.readFileSync(path.join(__dirname, '.env'), 'utf8').split('\n').forEach(line => {
    const m = line.match(/^([^#\s][^=]*)=(.*)/);
    if (m && !process.env[m[1].trim()]) process.env[m[1].trim()] = m[2].trim();
  });
} catch { /* no .env — rely on real environment */ }

// ── Collect Firebase config from env vars ───────────────────────────
const firebase = {
  apiKey:            process.env.FIREBASE_API_KEY             || '',
  authDomain:        process.env.FIREBASE_AUTH_DOMAIN         || '',
  projectId:         process.env.FIREBASE_PROJECT_ID          || '',
  storageBucket:     process.env.FIREBASE_STORAGE_BUCKET      || '',
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || '',
  appId:             process.env.FIREBASE_APP_ID              || '',
  measurementId:     process.env.FIREBASE_MEASUREMENT_ID      || '',
};

const apiBase = process.env.API_BASE || '/api';
const target = path.join(__dirname, 'src', 'environments', 'environment.prod.ts');
const haveConfig = firebase.apiKey && !firebase.apiKey.startsWith('YOUR_');

if (!haveConfig) {
  // No env vars (e.g. a local prod build without .env): emit placeholders so the
  // file always exists for Angular's fileReplacements. The app then falls back
  // to the in-browser setup screen instead of failing the build.
  console.warn(
    '\x1b[33m[setup-env] FIREBASE_API_KEY not set — writing placeholder ' +
    'environment.prod.ts. The app will use the in-browser setup screen.\x1b[0m'
  );
  for (const k of Object.keys(firebase)) {
    if (!firebase[k]) firebase[k] = 'YOUR_' + k.replace(/[A-Z]/g, c => '_' + c).toUpperCase();
  }
}

// ── Write environment.prod.ts ───────────────────────────────────────
const contents =
`// AUTO-GENERATED by setup-env.js at build time — do not edit by hand.
// Real values come from environment variables (FIREBASE_*); see setup-env.js.
export const environment = {
  production: true,
  apiBase: ${JSON.stringify(apiBase)},
  firebase: ${JSON.stringify(firebase, null, 2).replace(/\n/g, '\n  ')},
};
`;

fs.writeFileSync(target, contents);
if (haveConfig) {
  console.log(`[setup-env] Injected Firebase config for project "${firebase.projectId}" → ${path.relative(__dirname, target)}`);
}
